---
title: "List of Current and Former People in Our Lab"
---

* 122.	Sarah Ratke, B.S., Microbiology, 2027 – In progress
* 121.	Callum Daly, B.S., BMB, 2027 – In progress
* 120.	Sergio Lugo-Fraga, B.S., Biology, 2026 – In progress
* 119.	Mai See Thao, B.S., Microbiology, 2026 – In progress*
* 118.	Caleb Lawyer, B.S., Biology, 2025 - In progress
* 117.	Sonya Ivkovic, B.S., Computer Science, 2025 - In progress
* 116.	Emilie Bellinette, B.S., Anthropology, 2025 - In progress
* 115.	Amren Hossain, B.S., Informatics & Biology, 2025 - In progress
* 114.	Noor Omar Musad, B.S., Biology, 2024 – In progress
* 113.	Sophia Taylor, B.S., Psychology, 2024 - In progress
* 112.	Sophia Deligiannidis, B.S., Psychology, 2024 - In progress
* 111.	Nekeria Ransom, B.S., Biology, 2024 – 2025; M.S. MCB 2025 - In progress
* 110.	Deeksha Kavalapara, B.S., Informatics & Biology, 2024 - In progress
* 109.	Jazlynn Bailey, B.S., Biology, 2024 – In progress
* 108.	Rudra Malo, B.S., BMB, 2023 - 2024
* 107.	Ethan Li, B.S., Biology, 2023 - 2024
* 106.	Seojin Jung, B.S., Biology, 2023 - 2024
* 105.	Jared Gracia-David, B.S., Biology, 2022 - 2024
* 104.	Vartika Burman, Biology, 2023 - In progress
* 103.	Annabelle Kearney, B.S., Biology, 2023 - 2024
* 102.	Nishtha Lotan, B.S., Biology, 2023 - 2024
* 101.	João Tsai Silva, B.S., Biology, 2022 - 2024
* 100.	Journey Tamba, B.S., Biology, 2022 - 2023
* 99.	Isabel Rojas, B.S., Biology, 2022 - 2024
* 98.	Robert Li, B.S., Biology, 2022 - 2023
* 97.	Marie Beaulieu, B.S., Microbiology, 2022 - 2024
* 96.	Gabe Zenoun, B.S., Biology, 2022 - 2023
* 95.	Antonia Mukiibi, B.S., Biology, 2022 - 2023
* 94.	Max Campbell, B.S., Biology, 2021- 2023
* 93.	Isaac Collibee, B.S., Biology, 2022
* 92.	Rohan Alda, B.S., Biology, 2021-2022
* 91.	Kate Scott, B.S., BMB, 2021-2022
* 90.	Emiley Miller, B.S., Biology, 2021-2022
* 89.	Lauren Sleboda, B.S., Biology, 2021
* 88.	Shayra Castillo Romano, B.S., Biology, 2021-2022
* 87.	Manya Vivek, B.S., Biology, 2020-2021; M.S., MCB 2022 - 2024
* 86.	Sarah Tucker, B.S., Microbiology, 2021-2022; M.S., MCB 2020 – 2023
* 85.	Matt Finkelberg, B.S., Biology, 2021-2022; M.S., MCB 2022 - 2023
* 84.	Siddhi Advani, Postdoc, 2021
* 83.	Kelly Haas, Postdoc, 2020 - 2021
* 82.	Caroline Martin, B.S., Biology, 2020-2021; M.S., OEB 2021 - 2022
* 81.	Kate Newcomer, B.S., BMB, 2020-2022
* 80.	Dvir Blander, B.S., Mathematics, 2020-2021
* 79.	Lorene Stasiuk, B.S., Chemistry, 2020-2021
* 78.	Jessica Atuahene, B.S., Biology, 2020-2021
* 77.	Danaiijah Vilsaint, B.S., Biology, 2020-2021
* 76.	Bryanna Mathias, B.S., Biology, 2020-2021
* 75.	Benjamin Peters, B.S., Biology, 2020-2021
* 74.	Brooke Linnehan, B.S., Biology, 2020-2021; M.S., MCB 2021-2022
* 73.	Christopher Colvin, B.S., Biology, 2020-2021; M.S., MCB 2021-2022
* 72.	Siddhi Advani, Postdoc, 2020-2021
* 71.	Kelly Haas, Postdoc, 2020-2021
* 70.	Arianna Kazemi, B.S., BMB 2019-2020
* 69.	Hanna Choi, B.S., Biology, 2019-2021
* 68.	Eliza Holtz, B.S., Biology, 2019-2021
* 67.	Eva Trip, B.S., Biology, 2018-2019
* 66.	Andrea Dame, B.S., Microbiology, 2018-2020; M.S., Microbiology 2020-2021
* 65.	Lionel Forbes, B.S., Biology, 2018-2020
* 64.	Nathan Haywood, B.S., Biochemistry, 2018 - 2020
* 63.	Karen Luong, REU, LEE-SIP, B.S., Biology, 2018-2020
* 62.	Heidi Mannarino, Environmental Sciences, 2019
* 61.	Nadia L’Bahy, B.S., Biology, 2018
* 60.	Matthew Kuhl, REU, Collaborative Undergraduate Research in Energy Program 2018
* 59.	Victoria Thong, B.S., Biology, 2017-2018
* 58.	Aria Jordan, B.S., Biochemistry, 2017-2019
* 57.	Jacob Barnet, Ph.D., Organismal and Evolutionary Biology, 2017-2018
* 56.	Alexander Truchon, B.S., M.S., Microbiology, 2017-2019; M.S., Microbiology 2019-2020
* 55.	Nick Mucci, B.S., Biology, 2017
* 54.	Aaron Szczepanek, B.S., Biology, 2017
* 53.	Rebeca Bonilla, REU, Harvard Forest Summer Internships Ecological Research 2016
* 52.	Belle Henry, REU, Collaborative Undergraduate Research in Energy Program 2016
* 51.	Jonathan Hulvey, Ph.D., Research Assistant Professor, 2014-2017
* 50.	Lauren Alteio, Ph.D., Organismal and Evolutionary Biology, In Progress
* 49.	William Rodriguez, Ph.D., Organismal and Evolutionary Biology, 2014-2019
* 48.	Nadia Kianfar, B.S., Biology, 2017
* 47.	Kelly Haas, Ph.D., Microbiology 2016
* 46.	Kelly Callahan, B.S., Veterinary and Animal Sciences 2016
* 45.	Shane Lawson, B.S., BMB 2016
* 44.	Madhura Kulkarni, B.S., BMB 2016
* 43.	Fauzia Iqbal, B.S., Microbiology 2016
* 42.	Ava Bakhtyari, B.S., BMB 2016
* 41.	Josia DeChiara, REU, Harvard Forest Summer Internships Ecological Research 2015
* 40.	Cora Kerber, REU, Collaborative Undergraduate Research in Energy Program 2015
* 39.	Eric Gann, B.S., Biology, B.S., BMB 2015
* 38.	Jacob Mayfield, Ph.D., Research Fellow 2014 – 2015
* 37.	Josia DeChiara, B.S., Biology (Hampshire College), 2014-2015
* 36.	Ada Vilches, REU, Harvard Forest Summer Internships Ecological Research 2014
* 35.	Nuria Varela, REU, Collaborative Undergraduate Research in Energy Program 2014
* 34.	Sonia Filipczak, B.S., Public Health 2014
* 33.	Monique Tait, M.S., Microbiology 2014
* 32.	Maddy Coppi, Ph.D., Research Assistant Professor, 2010-2013
* 31.	Sonia Filipczak, REU, Harvard Forest Summer Internships Ecological Research 2014
* 30.	Farah Abdul-Rahman, M.S., Microbiology 2013
* 29.	Josephine Aiyeku, B.S., Microbiology 2013
* 28.	Megan Strough, M.S., Microbiology 2013
* 27.	Amy Biddle, Ph.D., Microbiology 2013
* 26.	James Hayes, M.S., Molecular and Cellular Biology, 2013
* 25.	Supratim Mukherjee, Ph.D., Microbiology, 2013
* 24.	Tara Mahendrarajah, B.S., Microbiology 2012
* 23.	Farah Abdul-Rahman, B.S., Microbiology 2012
* 22.	Ana Jenness, B.S., Microbiology 2012
* 21.	Deepti Sreepathi, B.S., Microbiology 2012
* 20.	Tara Mahendrarajah, REU, Harvard Forest Summer Internships Ecological Research 2011
* 19.	Kelden Pehr, REU, Harvard Forest Summer Internships Ecological Research 2011 
* 18.	Caitlin Lauer, B.S., Microbiology 2011
* 17.	Stephen Godin, B.S., Biology 2011
* 16.	Zhiyi Sun, Ph.D., Organismal and Evolutionary Biology 2011
* 15.	Michael Abdelshahid, REU, Institute for Cellular Engineering 2010
* 14.	Maria Campo, M.S., Molecular and Cellular Biology 2010
* 13.	Atamurad Chariyeva, B.S., Computer Science 2010
* 12.	Danielle Amisano, B.S., Microbiology 2009, M.S
* 11.	Elsa Petit, Ph.D., Postdoctoral Fellow 2010
* 10.	Volker Grabe, M.S., Microbiology 2010., Bioinformatics (visiting student from Germany)
* 9.	Jinghua Hu, Ph.D., Electrical and Computer Engineering 2008
* 8.	Igor Romashko, B.S., Biochemistry 2008, B.S., Computer Science 2008
* 7.	Supriya Deshpande, Intern 2007-2008
* 6.	Devin Currie, B.S., Microbiology 2007
* 5.	Benjamin Sanders, Microbiology (left after one year for medical school) 2007
* 4.	Angelle Aldridge, B.S., University Without Walls Off Campus 2007
* 3.	Ana Pereira, B.S., Microbiology 2005, M.S., Microbiology 2008
* 2.	Winnie Chen, B.S., Microbiology 2005, M.S., Microbiology 2006
* 1.	Andrew Tolopko, B.S., Computer Science 2005