---
title: "Publications"
---

<a href="https://scholar.google.com/citations?user=qSulmx8AAAAJ&hl=en" target="_blank">Google Scholar</a>

## University of Massachusetts Amherst

-   Pavlopoulos GA, Baltoumas FA, Liu S, Selvitopi O, Camargo AP, Nayfach S, Azad A, Roux S, Call L, Ivanova NN, Chen IM, Paez-Espino D, Karatzas E; Novel Metagenome Protein Families Consortium (including Blanchard JL); Iliopoulos I, Konstantinidis K, Tiedje JM, Pett-Ridge J, Baker D, Visel A, Ouzounis CA, Ovchinnikov S, Buluç A, Kyrpides NC (2023). Unraveling the functional dark matter through global metagenomics. Nature. 2023 Oct;622(7983):594-602. doi: 10.1038/s41586-023-06583-7.

-   Lee B, Neri U, Roux S, Wolf YI, Camargo AP, Krupovic M, RNA Virus Discovery Consortium (including Blanchard JL), Simmonds P, Kyrpides NC, Gophna U, Dolj VV, Koonin EV (2023) A vast world of viroid-like circular RNAs revealed by mining metatranscriptomes. Cell. 2023 Jan 21:S0092-8674(22)01582-3. doi: 10.1016/j.cell.2022.12.039. Also available on bioRxiv

-   Neri U, Wolf YI, Roux S, Camargo AP, Lee B, Kazlauskas D, Chen I-M, Ivanova N, Zeigler Allen L, Paez-Espino D, Bryant DA, Bhaya D, RNA Virus Discovery Consortium (including Blanchard JL), Krupovic M, Dolj VV, Kyrpides NC, Koonin EV, Gophna U (2022) Expansion of the global RNA virome reveals diverse clades of bacteriophages. Cell. 185:21(4023-4037) .e18. doi.org/10.1016/j.cell.2022.08.023

-   Fremin BJ, Bhatt AM, Kyrpides NC, Global Phage Small Open Reading Frame (GP-SmORF) Consortium (including Blanchard JL) (2022) Thousands of small, novel genes predicted in global phage genomes. Cell Reports. 39:12. doi.org/10.1016/j.celrep.2022.110984

-   Nayfach S, Roux S, Seshadri R, Udwary D, Varghese N, Schulz F, Wu D, Paez-Espino D, Chen IM, Huntemann M, Palaniappan K, Ladau J, Mukherjee S, Reddy TBK, Nielsen T, Kirton E, Faria JP, Edirisinghe JN, Henry CS, Jungbluth SP, Chivian D, Dehal P, Wood-Charlson EM, Arkin AP, Tringe SG, Visel A; IMG/M Data Consortium (including members of our lab Blanchard JL, Alteio LV, Rodriguez-Reillo W)), Woyke T, Mouncey NJ, Ivanova NN, Kyrpides NC, Eloe-Fadrosh EA (2021) A genomic catalogue of Earth's microbiome Nat Biotechnology 39(4):499-509. doi: 10.1038/s41587-020-0718-6.

-   Chowdhury PR, Golas S, Alteio LV, Billings AF, Jeffrey L. Blanchard JL, Melillo JM, DeAngelis KM (2021) The transcriptional response of soil bacteria to long-term warming and short-term seasonal fluctuations in a terrestrial forest. Front Microbiol. Aug 27;12:666558. doi: 10.3389/fmicb.2021.666558.

-   Pec GJ van Diepen LTA, Knorr M, Grandy AS, Melillo JM, DeAngelis KM, Blanchard JL, Frey SD (2021). Long-term soil warming selects for a unique fungal community with potential implications for soil carbon dynamics. Ecosphere. https://doi.org/10.1002/ecs2.3460

-   LaCroix R, Walpen N, Sander M, Tfaily MM, Blanchard JL, Keiluweit M (2021) Long-term Warming Decreases Redox Capacity of Soil Organic Matter. Environmental Science & Technology Letters. 2021, 8, 1, 92--97 doi: 10.1021/acs.estlett.0c00748

-   Haas KN and Blanchard JL (2020) Kineothrix. Bergey's Manual of Systematics of Archaea and Bacteria. doi: 10.1002/9781118960608.gbm01648

-   Andras, J, Rodriguez-Reillo W, Truchon A, Blanchard JL, Pierce E, Ballantine K (2020) Rewilding the small stuff: The effect of ecological restoration on the microbiome of wetland soils. FEMS Microbiol Ecol. 2020 Oct 2;96(10):fiaa144. doi: 10.1093/femsec/fiaa144.

-   Alteio L, Schulz F, Seshadri R, Varghese N, Rodriguez-Riello W, Ryan E, Goudeau D, Eichorst S, Malmstrom R, Bowers R, Katz L, Blanchard J, Woyke T (2020) Complementary Metagenomic Approaches Improve Reconstruction of Microbial Diversity in a Forest Soil. mSystems. 2020 Mar 10;5(2). pii: e00768-19. doi: 10.1128/mSystems.00768-19.

-   Haas KN, Blanchard JL (2020) Reclassification of the Clostridium clostridioforme and Clostridium sphenoides clades as Enterocloster gen. nov., and Lacrimaspora gen. nov., including reclassification of fifteen taxa. Int J Syst Evol Microbiol. 2020 Jan;70(1):23-34. doi: 10.1099/ijsem.0.003698.

-   Cole EF, Zandvakili OR, Blanchard JL, Etemadi F, Hashemi M, Xing B (2019) Investigating soil bacterial community composition and response to hardwood biochar amendment using quantitative PCR. Applied Soil Ecology. Apr;136:80-85. doi.org/10.1016/j.apsoil.2018.12.010

-   Schulz F, Alteio L, Goudeau D, Ryan E, Yu G, Malmstrom R, *Blanchard J,* Woyke T (2018) Hidden diversity of soil giant viruses. Nature Communications. Nov 19;9(1):4881. doi: 10.1038/s41467-018-07335-2.

-   Haas KN, Blanchard JL (2017) Kineothrix alysoides, gen. nov., sp. nov., a saccharolytic, butyrate-producer within the family Lachnospiraceae. ISJEM. Feb;67(2):402-410. doi: 10.1099/ijsem.0.001643.

-   Pold G, Billings AF, Blanchard JL, Burkhardt DB, Frey SD, Melillo JM, Schnabel J, van Diepen LT, DeAngelis KM (2016) Long-term warming alters carbohydrate degradation potential in temperate forest soils. Appl Environ Microbiol. Oct 27;82(22):6518-6530. doi: 10.1128/AEM.02012-16.

-   Tenaillon O, Barrick JE, Ribeck N, Deatherage DE, Blanchard JL, Dasgupta A, Wu GC, Wielgoss S, Cruveiller S, Médigue C, Schneider D, Lenski RE (2016) Tempo and mode of genome evolution in a 50,000-generation experiment. Nature. 536(7615):165-170. doi: 10.1038/nature18959.

-   Petit E, Coppi MV, Hayes JC, Tolonen A, Warnick T, Latouf WG, Amisano D, Biddle A, Mukherjee S, Ivanova, N, Lykidis A, Land M, Hauser L, Kripides N, Henrissat B, Lau J, Schnell D, Church G, Leschine SB, Blanchard JL (2015) Genome and transcriptome of Clostridium phytofermentans, catalyst for the direct conversion of plant feedstocks to fuels. PLoS ONE. 10(6): e0118285. doi: 10.1371/journal.pone.0118285

-   DeAngelis KM, Pold G, Topcuoglu BD, van Diepen LTA, Varney R, Blanchard JL, Melillo J, Frey SD (2015) Long-term forest soil warming alters microbial communities in temperate forest soils. Frontiers in Microbiology. 6:104. doi: 10.3389/fmicb.2015.00104 vBiddle AS, Leschine S, Huntemann M, Han J, Chen A, Kyrpides N, Markowitz V, Palaniappan K, Ivanova N, Mikhailova N, Ovchinnikova G, Schaumberg A, Pati A, Stamatis D, Reddy T, Lobos E, Goodwin L, Nordberg HP, Cantor MN, Hua SX, Woyke T, Blanchard JL (2014). The complete genome sequence of Clostridium indolis. Standards in Genome Sciences. Mar 18;9(3):1089-104

-   Sun Z, Blanchard JL (2014) Strong genome-wide selection early in the evolution of Prochlorococcus resulted in a reduced genome through the loss of a large number of small effect genes. PLoS ONE. Mar 3;9(3):e88837. doi: 10.1371/journal.pone.0088837

-   Mukherjee S, Thompson LK, Godin S, Schackwitz W, Lipzen A, Martin J, Blanchard JL (2014) Population level analysis of evolved mutations underlying improvements in plant cellulose and hemicellulose fermentation by Clostridium phytofermentans. PLoS One. Jan 22;9(1):e86731. doi: 10.1371/journal.pone.0086731

-   Biddle AS, Black SJ, Blanchard JL (2013) An in vitro model of the horse gut microbiome enables identification of lactate-utilizing bacteria that differentially respond to starch induction. PLoS ONE 8(10): e77599. doi:10.1371/journal.pone.0077599

-   Abdul-Rahman F, Petit E, Blanchard JL (2013) The Distribution of Polyhedral Bacterial Microcompartments Suggests Frequent Horizontal Transfer and Operon Reassembly. J Phylogen Evolution Biol. 1:e118

-   Biddle AS, Stewart L, Blanchard JL, Leschine SB (2013) Untangling the Genetic Basis of Fibrolytic Specialization by Lachnospiraceae and Ruminococcaceae in Diverse Gut Communities. Diversity 5(3), 627-640

-   Andrew C. Tolonen, Elsa Petit, Jeffrey L. Blanchard, Tom Warnick, Susan B. Leschine (2013). "Technologies to Study Plant Biomass Fermentation using the Model Bacterium Clostridium phytofermentans." Chapt 7 (pp 114-139) in "Biological Conversion of Biomass for Fuels and Chemicals: Explorations from Natural Utilization Systems". Edited by Jianzhong Sun, Shi-You Ding and Joy Peterson. The Royal Society of Chemistry.

-   Petit E, Latouf W, Coppi M, Currie D, Rhomasko I, Desphande S, Haas K, Alvelo-Maurosa JG, Wardman C, Schnell D, Leschine L, Blanchard J (2013) Involvement of a bacterial microcompartment in the metabolism of fucose and rhamnose by Clostridium phytofermentans. PLoS One. 8(1):e54337

-   Damery D, Hayes J, Blanchard JL (2010). The potential for production of ethanol from woody biomass by the microbe Clostridium phytofermentans. Wood Structures and Properties '10. Edited by Kúdela and Lagaňa. Arbora Publishers. p21-25

-   Hu J, Blanchard JL (2009) Environmental sequence data from the Sargasso Sea reveal that the characteristics of genome reduction in Prochlorococcus are not a harbinger for an escalation in genetic drift. Molecular Biology and Evolution. Jan;26(1):5-13

-   Lu S, Becker KA, Hagen MJ, Yan H, Roberts AL, Mathews LA, Schneider SS, Siegelmann HT, Macbeth KJ, Tirrell SM, Blanchard JL, Jerry DJ (2008) Transcriptional Responses to Estrogen and Progesterone in Mammary Gland Identify Networks Regulating p53 Activity. Endocrinology. Oct;149(10):4809-20

-   Gorham J, Parekh S, Leschine S (Main authors). Karem K, Fabel J, Blanchard JL (Contributing authors) (2008) Single-step production of cellulosic ethanol. Biofuels Technology. 1(Q4):37-44

-   Blanchard JL, Wholey WY, Conlon EM, Pomposiello PJ (2007) Rapid Changes in Gene Expression Dynamics in Response to Superoxide Reveal SoxRS-Dependent and Independent Transcriptional Networks. PLoS ONE. 2007 Nov 14;2(11):e1186

-   Richards TA, Dacks JB, Campbell SA, Blanchard JL, Foster PG, McLeod R, Roberts CW. Evolutionary origins of the eukaryotic shikimate pathway: gene fusions, horizontal gene transfer, and endosymbiotic replacements. Eukaryot Cell. 2006 Sep;5(9):1517-31

-   Conlon EM, Alpargu G, Blanchard JL (2006) Comparative genomics approaches for identifying genetic regulatory networks. Chance. 19:45-48

-   Blanchard JL (2004) Bioinformatics and Systems Biology, rapidly evolving tools for interpreting plant response to global change. Field Crops Research. 90:117-131

## National Center for Genome Resources

-   de Visser AJM, Hermisson J, Wagner, GP, Ancel LW, Bagheri-Chaichian H, Blanchard JL, Chao L, Cheverud JM, Elena SF, Fontana W, Gibson G, Hansen TF, Krakauer D, Lewontin RC, Ofria C, Rice SH, von Dassow G, Wagner A, Whitlock MC (2003) Evolution and detection of genetic robustness. Evolution. 57:1959-1972

-   Küffner RM, Gonzales M, Steadman P, Wlodek DK, Jankowitz RJ, Boinoff JR, Montoya AL, Peterson TF, Bulmore DL, Blanchard JL (2002) PathDB. Nucleic Acids Research Database Issue

-   Brinkman FSL, Blanchard JL, Greberg H, Wan I, De Koning A, Av-Gay Y, Brunham RC, Fernandez RC, Finlay BB, Otto SP, Ouellette BF, Keeling P, Hancock REW, Rose AM, SJM Jones (2002). Evidence that plant-like genes in Chlamydia species reflect an ancestral relationship between Chlamydiaceae, cyanobacteria, and the chloroplast. Genome Research. 12:1159-67

## University of Oregon

-   Blanchard JL, Lynch M (2000) Organelle Genes: why do organellar genes end up in the nucleus? Trends in Genetics. 16:315-320

-   de Visser AJM, Zeyl CW, Gerrish PJ, Blanchard JL, Lenski RE (1999) Diminishing returns from mutation supply rate in asexual populations. Science. 283:404-406

-   Lynch M, Blanchard JL, Houle D, Kibota T, Schultz S, Vassileva L, Willis J (1999) Spontaneous deleterious mutation. Evolution. 53:645663

-   Blanchard JL, Hicks JS (1999) The non-photosynthetic plastid in malarial parasites and other apicomplexans is derived from outside the green plastid lineage. Journal of Eukaryotic Microbiology. 46:367-375

-   Lynch M, Blanchard JL (1998) Deleterious mutation accumulation in organelle genomes. Genetica. 102/103:29-39

## University of Georgia

-   Bruns BU, Blanchard JL, Schmidt GW (1998) On the modulation of thylakoid structure and function upon adaptation to prolonged nitrogen-deficiency. Pp. 3081-3086 in Photosynthesis: Mechanisms and Effects (IV), G. Garab (ed), Kluwer Acad. Publ., Dordrecht

-   Blanchard JL, Schmidt GW (1996) Mitochondrial DNA migration events in yeast and mammals: integration by a common end-joining mechanism and alternative perspectives on nucleotide substitution patterns. Molecular Biology and Evolution. 13:537-548

-   Blanchard JL, Schmidt GW (1995) Pervasive migration of organellar DNA to the nucleus in plants. Journal of Molecular Evolution. 41:397-406

## Genentech Inc.

-   Chen AB, Championsmith AA, Blanchard JL, Niepelt BA, Federici MM, Formento J, Sinicropi DV (1992) Quantitation of E. coli protein impurities in recombinant human interferon. Applied Biochemistry and Biotechnology. 36:137-152

## Worcester Polytechnic Institute

-   Weathers PJ, Blanchard JL (1990) Multiple fruiting of the edible mushroom, Coprinus cinereus, from explants of the stipe. Applied Microbiology and Biotechnology. 33:652-656

-   Weathers PJ, Cheetham RD, Blanchard JL, Niedzielski J, Crusberg TC (1987) Biotraps for heavy metal removal and recovery from electroplating wastewater. Society for Industrial Micrbiology (SIM) News 37:9-11
