---
title: "Training and Lab Expectations"
---

# Welcome!

Welcome to the Blanchard research group. We have put together a lab manual to make expectations and responsibilities clear. If you have ideas about things to add, or what to clarify, let me know. When you join the lab, you're expected to read this manual and sign a form indicating that you have done so.

# Expectations and Responsibilities

## Big Picture

Science is hard. But it's also fun. In the Blanchard Lab, we want to make sure that everyone experiences a positive, engaging, challenging, and rewarding lab environment. To maintain that environment, we all have to do a few things.

-   Work on what you're passionate about, work hard at it, and be proud of it. Be so proud of it that you have to suppress bragging (but it's ok to brag sometimes).
-   Scientists have to be careful. Don't rush your work. Think about it. Implement it. Double and triple check it. Incorporate sanity checks. Ask others to look at your code or data if you need help or something looks off. It's ok to makes mistakes, but mistakes shouldn't be because of carelessness or rushed work.
-   If you do make a mistake, you should definitely tell your collaborators (if they have already seen the results, and especially if the paper is being written up, is already submitted, or already accepted). We admit our mistakes, and then we correct them and move on.
-   We all want to get papers published and do great things. But we do this honestly. It is never ok to plagiarize, tamper with data, make up data, omit data, or fudge results in any way. Science is about finding out the truth, and null results and unexpected results are still important. This can't be emphasized enough: no academic misconduct!
-   Support your fellow lab-mates. Help them out if they need help (even if you aren't on the project), and let them vent when they need to. Science is collaborative, not competitive. Help others, and you can expect others to help you when you need it.
-   Respect your fellow lab-mates. Respect their strengths and weaknesses, respect their desire for quiet if they need it, and for support and a kind ear when they need that. Respect their culture, their religion, their beliefs, their sexual orientation.
-   If you're struggling, tell someone (feel free to tell Jeff!). Your health and happiness come first. The lab looks out for the well-being of all its members. We are here to help. It's ok to go through hard patches (we all do), but you shouldn't feel shy about asking for help or just venting.
-   If there is any tension or hostility in the lab, something has to be done about it immediately. We can't thrive in an environment we aren't comfortable in, and disrespect or rudeness will not be tolerated in the lab. If you don't feel comfortable confronting the person in question, tell me.
-   If you have a problem with Jeff and are comfortable telling me about it, do! If you aren't comfortable, then tell the the graduate program director.
-   Stay up to date on the latest research, by using RSS feeds and/or getting journal table of contents. Also consider following scientists in the field on Twitter.
-   Remember the lab philosophy: "We like to do good science and have fun. At the same time, but also separately". Have a life outside of the lab, take care of your mental and physical health, and don't ever feel bad for taking time off work.

## Small Picture

There are a few day-to-day things to keep in mind to keep the lab running smoothly.

-   If you're sick, stay home and take care of yourself. Because you need it, and also because others don't need to get sick. If you're sick, reschedule your meetings and participants for the day (or the next couple of days) as soon as you can.
-   You aren't expected to come into lab on weekends and holidays, and you aren't expected to stay late at night. You are expected to get your work done (whatever time of day you like to do it).
-   Show up to your meetings, show up to your classes, and show up to lab meetings. You do not have to be in at 9am every day -- just show up for your commitments, and work the hours you need to work to get your researh done.
-   Make sure the door to the lab is locked if no one is inside. Turn off the lights if you're the last one leaving for the day.
-   Keep the lab tidy. Eating at your desk (but not in the lab) is fine, but clean up food waste, crumbs, spills. Put lab equipment back where you found it. Keep common areas uncluttered.
-   Dress code is casual. If you are working in the lab be sure to follow laboratory safety guidelines Principal Investigator All of the above, and I promise to also...
-   Be available in person and via e-mail on a regular basis, including regular meetings to discuss your research (and anything else you'd like to discuss)
-   Give my perspective on where the lab is going, where the field is going, and tips about surviving and thriving in academia
-   Support your career development by introducing you to other researchers in the field, promoting your work at talks, writing recommendation letters for you, and letting you attend conferences as often as finances permit
-   Help you prepare for the next step of your career, whether it's an industry job, graduate school, medical school, a post-doc, a faculty job, or a job outside of academia
-   Give you feedback on a timely basis, including feedback on project ideas, conference posters, talks, manuscripts, figures, grants
-   Support you (scientifically and financially)

## Graduate students

All of the above, and you will also be expected to

-   Develop your dissertation research. Your dissertation should have at least 3 substantial chapters that answer a big-picture question that you have. Much of your work has to be done independently, but remember that others in lab are there to help you when you need it and that manuscript publications can include collaborators.
-   Challenge me when I'm wrong or when your opinion is different, and treat the rest of the lab to your unique expertise.
-   Help mentor undergraduate students in the lab when they need it -- either because they ask, or because I ask you to.
-   Make sure you meet all departmental deadlines (e.g., for your exams and thesis)
-   Prioritize time for research. Coursework and TAing are important, but ultimately your research gets you your PhD and prepares you for the next stage of your career.
-   Apply for grants. It's in your best interest to get experience writing grants -- and if you get them, you'll be helping out the entire lab as well as yourself (because you'll free up funds previously allocated to you)
-   Apply for jobs (academic or otherwise) when you're ready, but no later than the beginning of your 4th year of graduate school. If you think you'd like to leave academia, that's completely ok -- but you should still treat your disseration seriously, and talk to me about how to best train for a job outside academia.
-   Present your work at departmental events, at other labs (if invited), and at conferences.

## Undergraduate Students

All of the above, and you will also be expected to - Assist other lab members with data collection and analysis (unless you are working on your own independent project under the mentorship of another lab member, in which case you should work on that). - Develop your weekly schedule by talking to your graduate student mentor or your post-doc mentor. You should be coming in every week, and scheduling enough time to get your work done. - If you are earning course credit for research, you must also attend lab meetings when your schedule permits, present at one of these lab meetings, and submit a write-up of your research by the end of the semester.

# Code of Conduct

## Essential Policies

The lab, and the university, is an environment that must be free of harassment and discrimination. All lab members are expected to abide by the University of Massachusetts Amherst policies on discrimination and harassment, which you can (and must) read about here - https://www.umass.edu/equalopportunity/. The lab is committed to ensuring a safe, friendly, and accepting environment for everybody. We will not tolerate any verbal or physical harassment or discrimination on the basis of gender, gender identity and expression, sexual orientation, disability, physical appearance, body size, race, or religion. We will not tolerate intimidation, stalking, following, unwanted photography or video recording, sustained disruption of talks or other events, inappropriate physical contact, and unwelcome sexual attention. Finally, it should go without saying that lewd language and behavior have no place in the lab, including any lab outings. If you notice someone being harassed, or are harassed yourself, tell Jeff immediately. If Jeff is the cause of your concern, then reach out to the department chair or another trusted faculty member in the department.

## Scientific Integrity

### Research (Mis)conduct

The lab, and University of Massachusetts Amherst, is committed to ensuring research integrity, and we take a hard line on research misconduct. We will not tolerate fabrication, falsification, or plagiarism. Read our university's policies on the conduct of research carefully - https://www.umass.edu/research/policy/responsible-conduct-research-trustee-policy-t08-10 A big problem is why people feel the need to engage in misconduct in the first place, and that's a discussion that we can have. If you are feeling pressured to succeed (publish a lot, publish in high impact journals), you should reach out and we can talk about it -- but this pressure is something we all face and is never an excuse to fabricate, falsify, or plagiarize. Also, think about the goal of science and why you are here: you're here to arrive at the truth, to get as close as we can to facts about microbes and their communities. Not only is research misconduct doing you a disservice, it's also a disservice to the field. And it risks your entire career. It is never right and never worth it. Don't do it.

## Reproducible Research

If you gave someone else your raw data, they should be able to reproduce your results exactly. This is critical, because if they can't reproduce your results, it suggests that one (or both) of you has made errors in the analysis, and the results can't be trusted. Reproducible research is an essential part of science, and an expectation for all projects in the lab. For results to be reproducible, the analysis pipeline must be organized and well documented. To meet these goals, you should take extensive notes on each step of your analysis pipeline. This means writing down how you did things every step of the way (and the order that you did things), from any pre-processing of the data, to running models, to statistical tests. It's also worth mentioning that you should take detailed notes on your experimental design as well. Additionally, your code should also be commented, and commented clearly. We all know what it's like to sit down, quickly write a bunch of code to run an analysis without taking time to comment it, and then having no idea what we did a few months down the road. Comment your code so that every step is understandable by an outsider. Finally, it is highly encouraged that you use some form of version control (e.g., Git in combination with GitHub) to keep track of what code changes you made and when you made them, as well as sharing code with others. The lab's GitHub is https://github.com/jeffreyblanchard/ and the lab's BitBucket is https://bitbucket.org/ourmicrobiome/ Reproducibility is related to replicability, which refers to whether your results can be obtained again with a different data set. That is, if someone ran your study again (with a different group of participants), do they get the same results? If someone ran a conceptually similar study, do they get the same results? Science grows and builds on replicable results -- one-off findings don't mean anything. Our goal is to produce research that is both reproducible and replicable.

## Authorship

We will follow the APA guidelines with respect to authorship: "Authorship credit should reflect the individual's contribution to the study. An author is considered anyone involved with initial research design, data collection and analysis, manuscript drafting, and final approval. However, the following do not necessarily qualify for authorship: providing funding or resources, mentorship, or contributing research but not helping with the publication itself. The primary author assumes responsibility for the publication, making sure that the data are accurate, that all deserving authors have been credited, that all authors have given their approval to the final draft; and handles responses to inquiries after the manuscript is published." At the start of a new project, the student or post-doc taking on the lead role can expect to be first author (talk to Jeff about it if you aren't sure). Jeff will typically be the last author, unless the project is primarily under the guidance of another PI and Jeff is involved as a secondary PI -- then Jeff will be second to last and the main PI will be last. Students and post-docs who help over the course of the project may be added to the author list depending on their contribution, and their placement will be discussed with all parties involved in the paper. If a student or post-doc takes on a project but subsequently hands it off to another student or post-doc, they will most likely lose first-authorship to that student or post-doc, unless co-first-authorship is appropriate. All of these issues will be discussed openly, and you should feel free to bring them up if you are not sure of your authorship status or want to challenge it.

## Old projects

If a student or post-doc collects a dataset but does not completely analyze it or write it after leaving the lab, Jeff will re-assign the project (if appropriate) to another person to expedite publication. In some cases are data sets are so large that there are additional projects that are not directly related to the dissertation that can be spun out. The person who collected the data will still be including as a co-author on publications (unless the entire data set is already published). This policy is here to prevent data (especially expensive data) from remaining unpublished.

# General Policies

## Hours

Being in lab is a good way of learning from others, helping others, building camaraderie, having fast and easy access to resources (and people) you need, and being relatively free from distractions at home (e.g., your bed or Netflix). That said, hours in academia are more flexible than other jobs -- but you should still treat it as a real job (40 hours/week) and show up to the lab. My primary concern is that you get your work done, so if you find that you are more productive at home (lab-mates can be chatty sometimes), feel free to work at home occasionally. If you have no meetings, no participants, and no other obligations that day, it might be a good day to work at home -- but you can't do this all the time, and I expect to see everyone in the lab on a regular basis. The only exception to this is lab managers / research assistants, who must keep more regular hours and be in lab 5 days a week (excluding vacations, doctor appointments, family issues, etc). I expect lab managers / research assistants to be in about 8 hours a day, starting around 9am or 10am and ending around 5pm or 6pm. For graduate students, I understand having to be away for classes and TA-ing, but show up to the lab on a regular basis when you don't have those obligations. To encourage lab interaction, try to be in most weekdays during 'peak' hours (assuming no other obligations) -- e.g., between 11am and 4pm. This is not a hard rule, you can work at home occasionally, and I understand other obligations. But keep it in mind.

## PI Office Hours

In addition to weekly meetings (see below), and occasionally dropping by the lab, you can find Jeff in his office. His door is almost always open; if it is, feel free to ask for a chat. He will always say yes, though sometimes he can only spare a couple of minutes. If his door is closed, assume that Jeff is either gone, in a meeting in his office, or does not want to be disturbed -- so please send a message (Slack or e-mail) rather than knocking.

## Communication

### E-mail

I use email as the primary means of communication, but for general lab discussion it is nice to have some level of open views of the discussions over time related to lab meetings, projects and papers. For this we will use Slack. A rule of thumb is if you want to get a hold of me quickly use email or phone or stop in. If you want to send me a summary of our weekly meeting send it on Slack or if you want to communicate with part or all of the lab use Slack.

### Slack

Slack will be used as the primary means of lab communication. When posting messages or looking for updates, check the appropriate channel: #general for lab announcements, #lab-meetings for notes or communication related to lab meetings, #papers for sharing links to lab-relevant papers and discussing them, #code-tips for sharing wisdom on code writing or asking (and answering) the coding questions of others, #genomic-methods for sharing wisdom on genome sequencing / analysis or asking (and answering) the questions of others, #stats to ask and answer questions about statistical analyses, and #random for non-work-related chatting that is best kept out of the work-related channels. Try to keep each channel on topic, so that people can subscribe only to the channels that concern them. For messages to one person or a small group, use direct messages. If you have to send attachments (e.g., papers) or send messages that include out-of-lab recipients, put in our GDrive and add a link on Slack. Full-time lab members should install Slack on their computers and/or phones. Part-time lab members should also check Slack regularly. You should of course feel free to ignore Slack on evenings and weekends -- and Jeff probably will, too!

### Google Drive

Please post lab related documents to Google Drive using the OurMicrobiome directory rather than including them in email attachments. You can then send a link to the file in your email or on Slack.

### Google Calendars

The lab has a lab calendar that include's Jeff work-related calendar. Ask me to share it if you haven't received an email yet.

## Meetings

### Weekly Lab Meetings

Weekly lab meetings (\~1 hours each) are meant to be a forum for trainees to present project ideas and/or data to get feedback from the rest of the group. Projects at any level of completion (or even not yet started!) can benefit from being presented. These lab meetings can also be used to talk about methods, statistical analyses, new papers, and career development. For paper discussions, everyone must come to lab meeting having read the paper and prepared with comments and questions to contribute. Some weeks we may explore a particular issue and have people read different papers -- in that case, come to lab meeting having read your paper and be prepared to summarize it for the group. Each trainee (RA, students, post-docs) is expected to present at least once every semester. These meetings are informal, and you can do what you wish with your slot -- just be prepared to contribute something substantive. Lab members are also expected to attend every meeting (obviously, illnesses, doctor appointments, family issues, etc are a valid reason for missing a meeting). Undergraduate students are encouraged to attend as often as possible (assuming it fits in their course schedule). Occasionally, we may have joint lab meetings with other faculty in the department -- these may be combined with our weekly lab meeting or an additional meeting. We will also use lab meetings (or ad-hoc scheduled meetings) to prepare for conference presentations and give people feedback on job talks or other external presentations. Lab meeting agendas and notes will be kept in the #lab-meetings channel on Slack. Individual Meetings At the beginning of each semester, we will set a schedule for weekly meetings. Each full-time lab member (RAs, graduate students, post-docs) will have a one-hour slot set aside to meet with Jeff. If scheduling conflicts arise (e.g., because of travel), we can try to reschedule for another day that week. If there is nothing to discuss, feel free to cancel the meeting or just drop by for a brief chat. Jeff will meet with undergraduate students as a group every week (or according to need); post-docs and graduate students should meet with their undergraduate mentee on a regular basis.

### Deadlines

One way of maintaining sanity in the academic work is to be as organized as possible. This is essential because disorganization will hurt you, it hurts your collaborators and people whose help you need. When it comes to deadlines, tell your collaborators as soon as possible when you know when a deadline is, and make sure they are aware of it the closer it gets. Don't be afraid to bug them about it (yes, bug Jeff as well). Give Jeff at least one week's notice to do something with a hard deadline that doesn't require a lot of time (e.g., reading/commenting on conference abstracts, filling out paperwork, etc). Give Jeff at least two weeks' notice to do something with a hard deadline that requires a lot of time (e.g., a letter of recommendation). For manuscript revisions and invited paper submissions (which have hard-ish deadlines), give her as much time as you can, because these will require multiple back-and-forths. For manuscript submissions (i.e., no hard deadline), you can still bug Jeff to give you feedback if he hasn't responded in a week or two -- papers are important!

### Presentations

Learning to present your research is important. Very few people will read your papers carefully (sad, but true) but you can reach a lot of people at conference talks and posters. Also, if you plan on staying in academia, getting a post-doc position and getting a faculty position both significantly depend on your ability to present your data. Even if you want to leave academia, presentations are likely to be an important part of your job. Additionally, every time you present your work, you are representing not just yourself but the entire lab. It is therefore highly encouraged that you seek out opportunities to present your research, whether it is at departmental talk series and events, to other labs (within or outside of Columbia), at conferences, or to the general public. If you are going to give a presentation (a poster or a talk), be prepared to give a practice presentation to the lab at least one week ahead of time (two weeks or more are advisable for conference presentations, and many weeks ahead of time are advisable for job talks, which require much refining). Practice talks will help you feel comfortable with your presentation, and will also allow you to get feedback from the lab and implement those changes well in advance of your real presentation. Templates for posters will be available, and you can use those as much or as little as you'd like. Some general rules for posters should be followed: minimize text as much as possible (if you wrote a paragraph, you're doing it wrong), make figures and text large and easy to see at a distance, label your axes, and make sure different colors are easily discriminable. Other than that, go with your own style. Jeff is also happy to share slides from talks if you would like to use a similar style. You'll get a lot of feedback on your talks in any case, but other people's slides might be helpful to you as you are setting up your talk. As with posters, feel free to go with your own style as long as it is polished and clear.

### Recommendation Letters

Letters of recommendation are extremely important for getting new positions and grants. You can count on Jeff to write you a letter if you have been in the lab at least one year (it's hard to really know someone if they have only been around for a few months). Exceptions can be made if students or post-docs are applying for fellowships shortly after starting in the lab. If you need a letter, notify Jeff as soon as possible with the deadline (see Deadlines for guidance), your CV, and any relevant instructions for the content of the letter. If the letter is for a grant, also include your specific aims. In some cases (especially if short notice is given), you may also be asked to submit a draft of a letter, which will be modified based on Jeff's experience with you and anything else that has to be added. This will ensure that the letter contains all the information you need, and that it is submitted on time.

## Open Science

We're all for open science, so lab members are encouraged (well, required) to share their code and data with others, whether they are in the lab or outside of it. Within lab, you can share your code and data whenever you like. But do not share your code or data with the outside world until you think (and Jeff agrees) that the lab has finished working with it. This gives us an opportunity to work with the data to meet our needs (including grant needs!) before releasing it for other people to use. Generally, we will try to make our data and code publicly available within one year of publishing the results (longer if work on the dataset is ongoing). Currently, the best option for sharing smaller datasets might be the Open Science Framework. We will also share our work with the world as soon as we ready, which means preprints! The lab policy is to upload a preprint of a manuscript simultaneously with initial submission to a journal. The preferred preprint servers are bioRxiv. We will also put PDFs of all our papers on the lab website, and you should share PDFs of your paper with whoever asks.

## Funding

Funding for the lab currently comes National Science Foundation, Department of Energy and USDA grants. If you need to buy something, or have to charge a grant for something, let Jeff know and he will oversee the process. At some point, you will likely be asked to provide a figure or two for a grant Jeff is writing, and/or provide feedback on the grant. You are entitled to read any grant Jeff has submitted, whether it is ultimately funded or not. Aside from being a good opportunity to learn how grants are written, this will also allow you to see his vision for the lab in the years ahead. Feel free to ask Jeff to see any of the grants.

## Acknowledgements

Some text on this page was taken directly from an older version of Mariam Aly's lab manual. Here is a link to Professor Aly's [current version](https://github.com/alylab/labmanual/blob/master/aly-lab-manual.pdf).

